name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            name: linux
            bin: devcon
          - os: macos-latest
            name: mac
            bin: devcon
          - os: windows-latest
            name: windows
            bin: devcon.exe

    runs-on: ${{matrix.os }}

    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: clippy
    - uses: actions/checkout@v2
    - name: build
      run: cargo build --release --locked
    - name: artifacts
      uses: actions/upload-artifact@v2
      with:
        name: devcon-${{matrix.name}}
        path: target/release/${{matrix.bin}}
        if-no-files-found: error


